# _config.yml
title: "Sandro Martinelli Reia"
email: "sandro.reia@alumni.usp.br"
description: >-
  Statistical physicist studying cities, migration dynamics, and agent-based modeling.

# IMPORTANT for https://sandroreia.github.io
url: "https://sandroreia.github.io"
baseurl: ""  # must be empty for a user site (username.github.io)

author:
  name: "Sandro M. Reia"
  avatar: "/assets/images/avatar.jpeg"
  bio: "Postdoctoral Research Fellow<br>George Mason University"
  location: "Fairfax, VA, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sandro.reia@alumni.usp.br"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=8T1-mIQAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SandroReia"

# Pinning a version is optional but recommended for stability
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Navigation (Top Bar)
main:
  - title: "About"
    url: "/"
  - title: "Publications"
    url: "/publications/"
  - title: "CV"
    url: "/assets/ReiaCV.pdf"
